global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: "upright"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9394"]
